// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodgMj1L5r6NHH-foYy94tGcXTNKB2j48',
    appId: '1:912904632709:web:600a52cdc7d77d22942cec',
    messagingSenderId: '912904632709',
    projectId: 'figma-study',
    authDomain: 'figma-study.firebaseapp.com',
    storageBucket: 'figma-study.appspot.com',
    measurementId: 'G-NLVEX2N6PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzFa2VgxBer8TLWkX0qqW_RVWRN1v3BjU',
    appId: '1:912904632709:android:fc20063ab95dc3e0942cec',
    messagingSenderId: '912904632709',
    projectId: 'figma-study',
    storageBucket: 'figma-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7cq2ut6NdD29lPcBWMdihHj3bIItoEnU',
    appId: '1:912904632709:ios:94fcfe4445281a37942cec',
    messagingSenderId: '912904632709',
    projectId: 'figma-study',
    storageBucket: 'figma-study.appspot.com',
    iosBundleId: 'com.example.figmaStudy',
  );
}
